# Fase 1: Build
FROM node:18 

WORKDIR /app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código fuente
COPY . .


EXPOSE 5000

# Comando por defecto para nginx (ya viene configurado)
CMD ["npm", "run", "dev"]
